---
title: "Tarea Coffee_Data"
---

## Variedades muestras de café

Se elaborará un conjunto de gráficos apartir de los datos extraídos de Coffee Quality Institute (CQI)

### Cargar Bibliotecas

```{r}
#| label: bibliotecas-uso
#| warning: false
#| message: false
#| code-fold: true
library(tidyverse)
library(plotly)
library(readr)
library(DT)
library(hrbrthemes)
library(ggthemes)
```

### Cargar los datos

```{r}
#| label: variables-datos 
#| warning: false
#| message: false
#| code-fold: true

library(readr)
library(DT)

variables_café <- read_delim(
  file = "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2023-i/main/datos/cqi/coffee-quality.csv",
  delim = ",",
  col_select = c(
    "Country_of_Origin",
    "Variety",
    "Color",
    "Altitude",
    "Total_Cup_Points"
  ),
  col_types = cols()
)

datatable(variables_café, options = list(
  pageLength = 5,
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json')
))


```

## Histograma

```{r}
#| label: variables-Histograma 
#| warning: false
#| message: false
#| code-fold: true

histograma_café <-
  variables_café |>
  ggplot(aes(x = Total_Cup_Points)) +
  geom_histogram(
    aes(
      text = paste0(
        "Puntaje total: ", round(after_stat(x), 2), "\n",
        "Frecuencia: ", after_stat(count)
      ),
      #Para agregar la línea
      
      y = after_stat(density) 
    ),
    bins = 20
  ) +
  geom_density(color = "#000080") +
  scale_y_continuous(labels = scales::label_comma()) +
  ggtitle("Distribucion por puntos otorgados a las plantas de café") +
  xlab("Total points") +
  ylab("Frecuencia") +
  labs(subtitle = "Datos de 206 plantas", caption = "Fuente: Coffee Quality Institute") +
  theme_ipsum_es()

ggplotly(histograma_café, tooltip = "text") |>
  config(locale = 'es')

```

## Grafico de dispercion

```{r}
#| label: Dispersión-datos 
#| warning: false
#| message: false
#| code-fold: true

dispersión_café <-
  variables_café |>
  ggplot(aes(x = Altitude, y = Total_Cup_Points)) +
  geom_point(aes(
    text = paste0(
      "Country: ", Country_of_Origin, "\n",
      "Altitude: ", round(Altitude, 2), "\n",
      "Total Points: ", round(Total_Cup_Points, 2), " puntos"
    )
  )) +
  geom_smooth(method = "lm") +
  ggtitle("Grafico de disperción del Total de puntos y la Altitud") +
  xlab("Altitud") +
  ylab("Total points") +
  labs(caption = "Fuente: Coffee Quality Institute") +
  theme_ipsum_es()  

# Gráfico de dispersión
ggplotly(dispersión_café, tooltip = "text") |>
  config(locale = 'es')
```


# Grafico de barras

```{r}
#| label: Grafico-datos 
#| warning: false
#| message: false
#| code-fold: true
#| 
grafico_caja<-
variables_café |>
  ggplot(aes(x = Color, y = Total_Cup_Points, color = Color )) +
  geom_boxplot() +
  ggtitle("Gráfico de caja de los porcentajes de las plantas de café") +
  ylab("Total points") +
  labs(subtitle = "Datos países", caption = "Fuente: Gapminder.org") +
  theme_ipsum_es() +
  theme(axis.text.x=element_blank() 
    )
  

# Gráfico de caja plotly
ggplotly(grafico_caja) |> 
  config(locale = 'es')
```
